version: '3.2'

services:
  syncthing:
    image: syncthing/syncthing
    restart: always
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - "syncthing-config:/var/syncthing/.config/syncthing"
      - "syncthing-data:/var/syncthing"

  jupyterlab-tensorflow:
    image: jupyter/tensorflow-notebook
    volumes:
     - "homecloud-jupyter:/notebooks"
    ports:
      - "18888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks

  homeassistant:
      image: homeassistant/home-assistant
      volumes:
        - homeassistant-config:/config
      ports:
        - "18123:8123"

  openhab:
    image: "openhab/openhab:3.0.0"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "openhab_addons:/openhab/addons"
      - "openhab_conf:/openhab/conf"
      - "openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    ports:
      - "28080:8080"
      - "28443:8443"

  grocy-nginx:
    image: "grocy/nginx:v3.0.0-1"
    depends_on:
      - grocy
    ports:
      - '22080:8080'
      - '22443:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx

  grocy:
    image: "grocy/grocy:v3.0.0-1"
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - grocy-db:/var/www/data
    env_file:
      - grocy.env

  grafana:
    image: grafana/grafana
    ports:
      - 13000:3000
    volumes:
      - homecloud-grafana:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    ports:
      - '18086:8086'
    volumes:
      - homecloud-influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=ds918
      - INFLUXDB_ADMIN_USER=synology
      - INFLUXDB_ADMIN_PASSWORD=synology

volumes:
  syncthing-config:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/syncthing/config
      o:         bind

  syncthing-data:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/syncthing/data
      o:         bind

  grocy-db:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/grocy
      o:         bind

  homecloud-grafana:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/grafana
      o:         bind
  homecloud-influxdb:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/influxdb
      o:         bind

  homecloud-jupyter:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/jupyter-notebooks
      o:         bind

  openhab_addons:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/openhab/addons
      o:         bind

  openhab_conf:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/openhab/conf
      o:         bind

  openhab_userdata:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/openhab/userdata
      o:         bind

  homeassistant-config:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/openhab/userdata
      o:         bind
