version: '3.2'

services:
  nextcloud-server:
    image: nextcloud:latest
    depends_on:
      - mariadb
    volumes:
      - nextcloud-app:/var/www
      # - nextcloud-app-config:/var/www/html/config
      # - nextcloud-app-custom_apps:/var/www/html/custom_apps
      # - nextcloud-app-data:/var/www/html/data
      # - nextcloud-app-themes:/var/www/html/themes
      # - /etc/localtime:/etc/localtime:ro
    environment:
      # - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb 
    ports:
      - '19000:80'
      
  mariadb:
    image: webhippie/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=nextcloud
      - MARIADB_USERNAME=nextcloud
      - MARIADB_PASSWORD=nextcloud
      - MARIADB_DATABASE=nextcloud
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - homecloud-mariadb-mysql:/var/lib/mysql
      - homecloud-mariadb-backup:/var/lib/backup
    ports:
      - '11000:3306'

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - homecloud-redis:/var/lib/redis

  collabora:
    image: collabora/code
    ports: 
     - 19980:9980
    cap_add:
      - MKNOD
    environment:
      - extra_params=--o:ssl.enable=false
      - username=admin 
      - password=admin

  grafana:
    image: grafana/grafana
    ports:
      - 13000:3000
    volumes:
      - homecloud-grafana:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    ports:
      - '18086:8086'
    volumes:
      - homecloud-influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=ds918
      - INFLUXDB_ADMIN_USER=synology
      - INFLUXDB_ADMIN_PASSWORD=synology

volumes:

  nextcloud-app:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/nextcloud
      o:         bind

  # nextcloud-app-data:
  #   driver:      local
  #   driver_opts:
  #     type:      none
  #     device:    /volume2/homecloud/nextcloud/app-data
  #     o:         bind

  # nextcloud-app-config:
  #   driver:      local
  #   driver_opts:
  #     type:      none
  #     device:    /volume2/homecloud/nextcloud/app-config
  #     o:         bind

  # nextcloud-app-custom_apps:
  #   driver:      local
  #   driver_opts:
  #     type:      none
  #     device:    /volume2/homecloud/nextcloud/app-custom_apps
  #     o:         bind

  # nextcloud-app-themes:
  #   driver:      local
  #   driver_opts:
  #     type:      none
  #     device:    /volume2/homecloud/nextcloud/app-themes
  #     o:         bind

  homecloud-mariadb-mysql:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/mariadb/mysql
      o:         bind

  homecloud-mariadb-backup:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/mariadb/backup
      o:         bind

  homecloud-grafana:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/grafana
      o:         bind
  homecloud-influxdb:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/influxdb
      o:         bind

  homecloud-redis:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/homecloud/redis
      o:         bind