version: '3.2'

services:
  oc-server:
    image: owncloud/server:latest
    restart: always
    ports:
      - "58080:8080"
    depends_on:
      - db
      - redis
    links:
      - "db:db"
      - "redis:redis"
    environment:
      - OWNCLOUD_DOMAIN=localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis


volumes:
  files:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/owncloud/files
      o:         bind
  mysql:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/owncloud/mysql
      o:         bind
  backup:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/owncloud/backup
      o:         bind
  redis:
    driver:      local
    driver_opts:
      type:      none
      device:    /volume2/owncloud/redis
      o:         bind
