FROM bitnami/spark

RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.959/aws-java-sdk-bundle-1.11.959.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.959.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar